version: "2"

services:
  deno:
    container_name: docker-deno
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
    networks: 
      - deno
    
networks:
    deno:
      external: true